---
- name: Cisco ASA Add User.
  hosts: asa
  gather_facts: false
  connection: local

  tasks:
  - name: Cisco ASA Add User.
    asa_command:
      commands:
        - sh run | i hostname
        - sh run | i username

    register: print_output

  - debug: var=print_output
