---
- name: Cisco ASA Add User.
  hosts: asa
  gather_facts: false
  connection: local

  tasks:
  - name: Cisco ASA Add User.
    asa_config:
      commands:
        - config t
        - username 100233 password ChangeMe2019 privilege 15
        - username 100271 password ChangeMe2019 privilege 15

    register: print_output

  - debug: var=print_output
