---
- name: Cisco ASA Inventory.
  hosts: asa
  gather_facts: false
  connection: local

  tasks:
  - name: Cisco ASA Inventory.
    asa_command:
      commands:
        - sh version
        - sh inventory

    register: print_output

  - debug: var=print_output
