---
- name: WM5 save
  hosts: wm5
  gather_facts: false
  connection: local

  tasks:
  - name: WM5 save
    ios_command:
      commands:
        - sh run | i hostname
        - wr

    register: print_output

  - debug: var=print_output
