---
- name: Cisco Nexus Verify User.
  hosts: nexus
  gather_facts: false
  connection: local

  tasks:
  - name: Cisco Nexus Verify User.
    nxos_command:
      commands:
        - sh run | i hostname
        - sh run | i username

    register: print_output

  - debug: var=print_output
