---
- name: Palo Alto PANOS Verify System.
  hosts: paloalto
  connection: local

  tasks:
  - name: Palo Alto PANOS Verify System.
    panos_op:
      commands:
        - show system info
        - show system disk-space
        - show interfaces all

    register: print_output

  - debug: var=print_output
